FROM    java:openjdk-8-jre-alpine as languagetool

ENV VERSION=4.4
ADD https://www.languagetool.org/download/LanguageTool-$VERSION.zip /LanguageTool-$VERSION.zip

RUN apk --update add unzip \
    && unzip LanguageTool-$VERSION.zip \
    && rm LanguageTool-$VERSION.zip

WORKDIR /LanguageTool-$VERSION

VOLUME ["/LanguageTool-$VERSION/language-model"]